azure:
  resource_group: "mlops-heart-rg"
  workspace_name: "mlops-heart-aml-ws"
  location: "southeastasia"

storage:
  account_name: "mlopsheartstor4enbsn"
  container_name: "dvc-data"

feature_store:
  resource_name: "heart-disease-fs"
  name: "heart-disease-features"
  version: "1.0"
