apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: heart-disease

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

commonLabels:
  project: heart-disease-prediction
  managed-by: kustomize
